defaultPortal: hs-cms-uj
portals:
  - name: hs-cms-uj
    portalId: 25475053
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CKW_pJDnLxIJAA0AAAAA4A0DGO3vkgwg8LujAiju6QwyFBzCV3cm5ndTDT7A_2nrGtee3X1EOigAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgQhTQ35pNeG07DFwcArMazRddLAunoEoDZXUxUgBaAA
        expiresAt: '2022-01-19T11:11:47.627Z'
    personalAccessKey: >-
      CiRldTEtMzZkYy00MjVlLTRhYjQtODRhYS04ZmM4M2IxY2Q5NjkQ7e-SDBjwu6MCKhkABeaRgpNny-FGVgxNEPECeXRP_95pFrGTSgNldTE
